name: Analisis de seguridad con Bandit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  bandit-security:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar Bandit
        run: pip install bandit

      - name: Ejecutar analisis Bandit
        run: bandit -r . -x venv
